### ISSUE TITLE
Meta: speed ups

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#267]
- [x] https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/266
- [x] #264 
- [x] #260 
- [x] #259 
- [x] #268
- [x] #269
- [x] #270
- [x] https://github.com/openclimatefix/nowcasting_datamodel/issues/237
- [ ] https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/271
- [ ] https://github.com/openclimatefix/nowcasting_datamodel/issues/240

**Comment by peterdudfield** [comment]
Ill close this for the moment, and leave the others issues open
